# Generated by Django 4.1.2 on 2022-10-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_web_own'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='own',
            new_name='web',
        ),
    ]
