# Generated by Django 4.1.2 on 2022-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_own_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='web',
            name='lastname',
        ),
        migrations.AddField(
            model_name='web',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='web',
            name='number',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
